name: SpawnMe
author: jummes
main: com.github.jummes.spawnme.core.SpawnMe
version: 1.0
api-version: 1.14
commands:
  setspawn:
  spawn:
  spawns:
  spawnme:
permissions:
  spawnme.admin.setspawn:
    description: /setspawn command permission
    default: op
  spawnme.admin.help:
    description: /spawnme help command permission
    default: op
  spawnme.admin.reload:
    description: /spawnme reload command permission
    default: op
  spawnme.admin.menu:
    description: /spawnme menu command permission
    default: op
  spawnme.admin.spawns:
    description: /spawnme spawns command permission
    default: op
  spawnme.admin.*:
    description: wildcard admin permission
    default: op
    childen:
      spawnme.admin.setspawn: true
      spawnme.admin.help: true
      spawnme.admin.reload: true
      spawnme.admin.menu: true
      spawnme.admin.spawns: true
  spawnme.spawn.spawns:
    description: /spawns command permission